- name: Manage anvil container on the first remote node
  run_once: true
  tags:
    - anvil
  block:
    - name: Ensure previous anvil container is removed
      docker_container:
        name: anvil
        state: absent

    - name: Create directory for anvil state on host
      file:
        path: /var/lib/anvil-state
        state: directory
        owner: '1000'
        group: '1000'
        mode: '0755'

    - name: Run anvil container
      docker_container:
        name: anvil
        image: "ghcr.io/foundry-rs/foundry:v1.4.0"
        restart_policy: always
        entrypoint: anvil
        command:
          - --host
          - 0.0.0.0
          - --gas-price
          - "0"
          - --block-base-fee-per-gas
          - "0"
#          - --block-time
#          - "1"
          - --state
          - /state/anvil-state.json
          - --state-interval
          - "10"
          - --disable-min-priority-fee
          - -v
        network_mode: host
        volumes:
          - /var/lib/anvil-state:/state
        detach: true
        state: started

    - name: Wait for anvil to start
      pause:
        seconds: 15

    - name: Get private key from anvil logs
      shell: "docker logs anvil 2>&1 | grep -A 10 'Private Keys' | grep '(0)' | awk '{print $2}'"
      register: key_output
      changed_when: false

- name: Set anvil_private_key fact
  run_once: true
  set_fact:
    anvil_private_key: "{{ key_output.stdout | trim }}"
  tags:
    - anvil

- name: Expose anvil_private_key to 127.0.0.1 for subsequent plays
  set_fact:
    anvil_private_key: "{{ anvil_private_key }}"
  delegate_to: 127.0.0.1
  delegate_facts: true
  run_once: true

- name: Save anvil_private_key to group vars
  lineinfile:
    path: "{{ playbook_dir }}/group_vars/all"
    create: yes
    regexp: "^anvil_private_key:"
    line: "anvil_private_key: '{{ anvil_private_key }}'"
  run_once: yes
  delegate_to: localhost
  tags:
    - anvil
