- name: Download contracts from digitalocean to local machine
  get_url:
      url: "{{ manager_contracts }}" 
      dest: "files/manager.json"
      mode: 0644

- name: Set hosts
  set_fact: hosts="{{ hosts|default([]) + [ item.value['ansible_host'] ] }}"
  with_dict: "{{ hostvars }}"
  tags: save_base_keys

- name: Execute setup_validators script
  script: setup_validators.py
  environment:
    BASE_DIR: "files"
    SKALE_AMOUNT: "0"
    NODE_ETH_AMOUNT: "{{ node_eth_amount }}"
    ETH_PRIVATE_KEY: "{{ eth_private_key }}"
    ENDPOINT: "{{ endpoint }}"
    VALIDATOR_NAME: "{{ validator_name }}"
    MIN_DELEGATION_AMOUNT: "0"
    COMMISSION_RATE: "1"
    NODES_NUMBER: "{{ hosts|length }}"
  args:
    executable: python3
  tags: setup_validators


