- name: Download contracts from digitalocean to local machine
  get_url:
      url: "{{ manager_contracts }}" 
      dest: "files/manager.json"
      mode: 0644

- name: Set hosts
  set_fact: hosts="{{ hosts|default([]) + [ item.value['ansible_host'] ] }}"
  with_dict: "{{ hostvars }}"
  tags: save_base_keys

- name: Execute setup_validators script
  script: setup_validators.py
  environment:
    BASE_DIR: "files"
    SKALE_AMOUNT: "5"
    ETH_AMOUNT: "5"
    ETH_PRIVATE_KEY: "{{ eth_private_key }}"
    ENDPOINT: "{{ endpoint }}"
    MIN_DELEGATION_AMOUNT: "0"
    COMMISSION_RATE: "1"
    NODES_NUMBER: "{{ hosts|length }}"
  args:
    executable: python3
  tags: setup_validators


- name: Save base keys to remote servers 
  command: 'ssh -i {{ pem_cert_path }} ubuntu@{{ item.0 }} "echo {{ item.1 }} | sudo tee {{ base_path }}/base_key.txt"'
  with_together:
    - "{{ hosts }}"
    - "{{ lookup('file', 'files/base-keys.txt').splitlines() }}"
  tags: save_base_keys
