- name: Get skale wallet info output 
  command: "skale wallet info -f json"
  register: wallet_data_json
  environment:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  
- name: Get validator base private key
  command: cat "{{ base_path }}/base_key.txt"
  register: validator_key

- name: Get wallet data from json 
  set_fact: 
    wallet_data: "{{ wallet_data_json.stdout | to_json | from_json }}"

- name: Link address to validator
  become: yes
  script:
    cmd: link_address.py "{{ wallet_data.address }}"
  environment:
    ETH_PRIVATE_KEY: "{{ validator_key.stdout }}"
    ENDPOINT: "{{ endpoint }}"
    BASE_DIR: "{{ base_path }}"
  args:
    executable: python3
