- name: Get skale wallet info output
  command: "skale wallet info -f json"
  register: wallet_data_json
  environment:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  
- name: Get wallet data from json
  set_fact:
    wallet_data: "{{ wallet_data_json.stdout | to_json | from_json }}"

- name: Get validator id
  set_fact:
    validator_id: "{{ lookup('file', 'validator-id') }}"

- debug: msg="Validator id {{ validator_id }}"

- name: Sign validator id
  become: yes
  command:
    cmd: "skale node signature {{ validator_id }}"
  register: signature
  environment:
    LANG: en_US.utf-8
    LC_ALL: en_US.utf-8

- name: Save wallet address
  copy:
    content: "{{ wallet_data.address }}"
    dest: "{{ base_path }}/address"

- name: Save signature
  copy:
    content: "{{ signature.stdout.split()[1] }}"
    dest: "{{ base_path }}/signature"
