- name: Run Vagrant VMs on bare metal
  hosts: server
  roles:
    - role: vagrant
  tags:
    - vagrant
    
- name: Generate hosts file for node provision
  hosts: 127.0.0.1
  connection: local
  serial: 1
  roles:
    - role: generate_hosts
  tags:
    - hosts

- name: Generate scripts for restart VM on host
  hosts: 127.0.0.1
  connection: local
  serial: 1
  tasks:
    - import_role:
        name: restart_script
        tasks_from: generate_script
  tags:
    - restart_vms_scripts

- name: Add script and service to host and then run
  hosts: server
  become: true
  tasks:
    - import_role:
        name: restart_script
        tasks_from: copy_script
  tags:
    - restart_vms_scripts