- name: Deploy IMA contracts (this may take a while, logs - {{ playbook_dir }}/logs/ima-deploy.log)
  shell: bash {{ playbook_dir }}/../../helper-scripts/deploy_ima.sh 2>&1 | tee {{ playbook_dir }}/logs/ima-deploy.log
  run_once: yes
  environment:
    IMA_TAG: "{{ ima_tag }}"
    ETH_PRIVATE_KEY: "{{ eth_private_key }}"
    ENDPOINT: "{{ endpoint }}"
    GAS_PRICE: "{{ deploy_gas_price }}"
  tags:
    - deploy_ima

- name: Get IMA Contract Address
  shell: "jq -r '.message_proxy_mainnet_address' {{ playbook_dir }}/../../helper-scripts/contracts_data/ima.json"
  register: ima_address_output
  changed_when: false
  tags:
    - upload_ima

- name: Save IMA Contract Address to variable
  set_fact:
    ima_contracts: "{{ ima_address_output.stdout }}"
  tags: upload_ima

- name: Save IMA URL to group vars
  lineinfile:
    path: "{{ playbook_dir }}/group_vars/all"
    insertafter: EOF
    regexp: "^ima_contracts:"
    line: 'ima_contracts: "{{ ima_contracts }}"'
    state: present
  tags:
    - upload_ima
