- name: Deploy IMA contracts (this may take a while, logs - {{ playbook_dir }}/logs/ima-deploy.log)
  shell: bash {{ playbook_dir }}/../../helper-scripts/deploy_ima.sh 2>&1 | tee {{ playbook_dir }}/logs/ima-deploy.log
  run_once: yes
  environment:
    IMA_TAG: "{{ ima_tag }}"
    ETH_PRIVATE_KEY: "{{ eth_private_key }}"
    ENDPOINT: "{{ endpoint }}"
    GAS_PRICE: "{{ deploy_gas_price }}"
  tags:
    - deploy_ima

- name: Get SM Contract Address
  shell: "jq -r '.message_proxy_mainnet_address' {{ playbook_dir }}/../../helper-scripts/contracts_data/ima.json"
  register: ima_address
  tags:
    - upload_ima

- name: Save IMA URL to group vars
  lineinfile:
    path: "{{ playbook_dir }}/group_vars/all"
    insertafter: EOF
    regexp: "^ima_address:"
    line: "ima_address: {{ ima_address.stdout }}"
    state: present
  tags:
    - upload_ima
