- name: Deploy contracts
  command: bash {{ playbook_dir }}/../../helper-scripts/deploy_manager.sh
  run_once: yes
  environment:
    MANAGER_TAG: "{{ manager_tag }}"
    ETH_PRIVATE_KEY: "{{ eth_private_key }}"
    ENDPOINT: "{{ endpoint }}"
    GAS_PRICE: "{{ deploy_gas_price }}"
    NETWORK: "custom"
  tags:
    - deploy_sm
    - deploy_contracts
- name: Copy to s3
  aws_s3:
    aws_access_key: "{{ aws_key }}"
    aws_secret_key: "{{ aws_secret }}"
    bucket: "skale-abis"
    #bucket: skale-binaries
    src: "{{ playbook_dir }}/../../helper-scripts/deploy_manager.sh"
    object: 'skale-manager'
    region: 'eu-central-1'
    mode: put
    # overwrite: "no"
    permission: "public-read"
    ignore_nonexistent_bucket: True
  tags:
    - upload_contracts
