- name: Deploy manager contracts (this may take a while, logs - {{ playbook_dir }}/logs/sm-deploy.log)
  shell: bash {{ playbook_dir }}/../../helper-scripts/deploy_manager.sh 2>&1 | tee {{ playbook_dir }}/logs/sm-deploy.log
  run_once: yes
  environment:
    MANAGER_TAG: "{{ manager_tag }}"
    ETH_PRIVATE_KEY: "{{ eth_private_key }}"
    ENDPOINT: "{{ endpoint }}"
    GAS_PRICE: "{{ deploy_gas_price }}"
    NETWORK: "custom"
    ETHERSCAN: "{{ etherscan }}"
  tags: deploy_sm

- name: Copy SM ABI
  copy:
    src: "{{ playbook_dir }}/../../helper-scripts/contracts_data/manager.json"
    dest: "{{ playbook_dir }}/../../helper-scripts/contracts_data/skaleManagerComponents.json"
  tags: upload_sm

- name: Ensure group vars all
  file:
    state: touch
    path: "{{ playbook_dir }}/group_vars/all"
  tags: upload_sm

- name: Get SM Contract Address
  shell: "jq -r '.skale_manager_address' {{ playbook_dir }}/../../helper-scripts/contracts_data/manager.json"
  register: sm_address_output
  changed_when: false
  tags: upload_sm

- name: Save SM Contract Address to variable
  set_fact:
    manager_contracts: "{{ sm_address_output.stdout }}"
  tags: upload_sm

- name: Save SM URL to group vars
  lineinfile:
    path: "{{ playbook_dir }}/group_vars/all"
    insertafter: EOF
    regexp: "^manager_contracts:"
    line: 'manager_contracts: "{{ manager_contracts }}"'
    state: present
  tags: upload_sm

- name: Hotfix for zero node in Mirage
  run_once: yes
  script: fix_zero_node_mirage.py
  environment:
    BASE_DIR: "files"
    ETH_PRIVATE_KEY: "{{ eth_private_key }}"
    ENDPOINT: "{{ endpoint }}"
    MANAGER_CONTRACTS: "{{ manager_contracts }}"
  args:
    executable: python3
  when: node_type == "mirage_boot"
  tags: fix_zero_node