- name: Set endpoint for anvil
  set_fact:
    endpoint: "http://{{ hostvars[groups['nodes'][0]].ansible_host }}:8545"
  run_once: true
  when: anvil is defined and anvil
  tags: [deploy_sm, anvil]

- name: Save endpoint for anvil to group vars
  lineinfile:
    path: "{{ playbook_dir }}/group_vars/all"
    create: yes
    regexp: "^endpoint:"
    line: "endpoint: {{ endpoint }}"
  run_once: yes
  when: anvil is defined and anvil
  tags: [deploy_sm, anvil]

- name: Publish endpoint to all nodes for subsequent plays
  set_fact:
    endpoint: "{{ endpoint }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['nodes'] }}"
  run_once: true
  when: anvil is defined and anvil
  tags: [deploy_sm, anvil]


- name: Deploy manager contracts (this may take a while, logs - {{ playbook_dir }}/logs/sm-deploy.log)
  shell: bash {{ playbook_dir }}/../../helper-scripts/deploy_manager.sh 2>&1 | tee {{ playbook_dir }}/logs/sm-deploy.log
  run_once: yes
  environment:
    MANAGER_TAG: "{{ manager_tag }}"
    ETH_PRIVATE_KEY: "{{ eth_private_key }}"
    ENDPOINT: "{{ endpoint }}"
    GAS_PRICE: "{{ deploy_gas_price }}"
    NETWORK: "custom"
    ETHERSCAN: "{{ etherscan }}"
  tags: deploy_sm

- name: Copy SM ABI
  copy:
    src: "{{ playbook_dir }}/../../helper-scripts/contracts_data/manager.json"
    dest: "{{ playbook_dir }}/../../helper-scripts/contracts_data/skaleManagerComponents.json"
  tags: upload_sm

- name: Get SM Contract Address
  shell: "jq -r '.skale_manager_address' {{ playbook_dir }}/../../helper-scripts/contracts_data/manager.json"
  register: sm_address_output
  changed_when: false
  tags: upload_sm

- name: Save SM Contract Address to variable
  set_fact:
    manager_contracts: "{{ sm_address_output.stdout }}"
  tags: upload_sm

- name: Save SM URL to group vars
  lineinfile:
    path: "{{ playbook_dir }}/group_vars/all"
    create: yes
    regexp: "^manager_contracts:"
    line: "manager_contracts: {{ manager_contracts }}"
  tags: upload_sm

- name: Set allowed_ts_diff based on anvil variable
  set_fact:
    allowed_ts_diff: "{{ -1 if anvil is defined and anvil else 300 }}"
  run_once: yes
  tags: fix_zero_node

- name: Save allowed_ts_diff to group vars
  lineinfile:
    path: "{{ playbook_dir }}/group_vars/all"
    create: yes
    regexp: "^allowed_ts_diff:"
    line: "allowed_ts_diff: {{ allowed_ts_diff }}"
  run_once: yes
  tags: fix_zero_node


- name: Hotfix for zero node in Fair
  run_once: yes
  script: fix_zero_node_fair.py
  environment:
    BASE_DIR: "files"
    ETH_PRIVATE_KEY: "{{ eth_private_key }}"
    ENDPOINT: "{{ endpoint }}"
    MANAGER_CONTRACTS: "{{ manager_contracts }}"
    ALLOWED_TS_DIFF: "{{ allowed_ts_diff }}"
  args:
    executable: python3
  tags: fix_zero_node
