- name: Set allowed_ts_diff based on anvil variable
  set_fact:
    allowed_ts_diff: "{{ -1 if anvil is defined and anvil else 300 }}"
  run_once: yes

- name: Transfer funds from the base anvil account to main one
  run_once: yes
  tags: anvil_funds
  ansible.builtin.script: transfer_funds.py
  environment:
    ETH_PRIVATE_KEY: "{{ anvil_private_key }}"
    TARGET_PRIVATE_KEY: "{{ eth_private_key }}"
    ENDPOINT: "{{ endpoint }}"
    BASE_DIR: "files"
    AMOUNT: "{{ anvil_base_funds_amount | default(10) }}"
    ALLOWED_TS_DIFF: "{{ allowed_ts_diff }}"
  args:
    executable: python3
