- name: Set grafana and prometheus host base directories
  set_fact:
    grafana_path: "{{ base_path }}/monitoring/grafana"
    prom_path: "{{ base_path }}/monitoring/prom"
    influx_path: "{{ base_path }}/monitoring/influx"
    vm_path: "{{ base_path }}/monitoring/vm"


- name: Create base directories
  file:
    state: directory
    path: "{{ item.0 }}/{{ item.1 }}"
    mode: u+rwx,g+rwx,o+rwx
  loop: "{{ [grafana_path, prom_path, influx_path, vm_path] | product(['config', 'data']) | list }}"


- name: Set metirics ports
  set_fact:
    ports: ["9144", "9256", "9100", "8080"]


- name: Save node ips
  set_fact:
    node_ips: "{{ node_ips|default([]) + [hostvars[item].ansible_host] }}"
  loop: "{{ query('inventory_hostnames', 'nodes') }}"


- name: Save prometheus config
  set_fact:
    prometheus_config: |
      global:
        scrape_interval: 15s
        evaluation_interval: 15s

      scrape_configs:
        - job_name: net-monitor
          scrape_interval: 5s
          static_configs:
            - targets: {{ node_ips| product(ports) | map("join", ":") | list }}

        - job_name: telegraf
          scrape_interval: 5s
          static_configs:
            - targets: ['10.3.155.127:9279']


- name: Save grafana config
  set_fact:
    grafana_config: |
      [plugins]
        allow_loading_unsigned_plugins = victoriametrics-datasource


- name: Save prometheus config
  copy:
    content: "{{ prometheus_config }}"
    dest: "{{ prom_path }}/config/prometheus.yml"


- name: Save influx config
  set_fact:
    influx_config: |
      query-concurrency = 20
      query-queue-size = 15
      session-length = 120
      http-bind-address = ":2359"
      database = "metrics"


- name: Save VM config
  set_fact:
    vm_config: |
      database = "metrics"


- name: Save grafana config
  copy:
    content: "{{ grafana_config }}"
    dest: "{{ grafana_path }}/config/grafana.ini"


- name: Save influx config
  copy:
    content: "{{ influx_config }}"
    dest: "{{ influx_path }}/config/config.toml"


- name: Save influx config
  copy:
    content: "{{ vm_config }}"
    dest: "{{ vm_path }}/config/config.toml"


- name: Setup prometheus container
  docker_container:
    name: "prom"
    image: bitnami/prometheus:2.49.1
    ports: 9090
    state: started
    memory: 1GB
    network_mode: host
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - "{{ prom_path }}/data:/prometheus"
      - "{{ prom_path }}/config:/etc/prometheus"


- name: Setup influxdb container
  docker_container:
    name: "influx"
    image: influxdb:2.7.5
    ports: 2359
    state: started
    memory: 2GB
    network_mode: host
    volumes:
      - "{{ influx_path }}/data:/var/lib/influxdb2"
      - "{{ influx_path }}/config:/etc/influxdb2"
    env:
      INFLUXD_CONFIG_PATH: "/etc/influxdb2/config.toml"


- name: Setup vm container
  docker_container:
    image: victoriametrics/victoria-metrics
    name: vm
    state: started
    ports: 8428
    state: started
    network_mode: host
    memory: 1GB
    volumes:
      - "{{ vm_path }}/data:/victoria-metrics-data"
        # - "{{ vm_path }}/config:/victoria-metrics-data"


- name: Setup grafana container
  docker_container:
    name: "grafana"
    image: grafana/grafana:10.0.3
    ports: 3000
    state: started
    memory: 2GB
    network_mode: host
    command:
      - '--config=/etc/grafana/grafana.ini'
    volumes:
      - "{{ grafana_path }}/data:/opt/grafana/data"
      - "{{ grafana_path }}/config:/etc/grafana"
