- name: Run skale node init
  command: 
    chdir: "{{ base_path }}/skale-node-cli"
    cmd: "skale node init  --install-deps --env-file {{ base_path }}/skale-node-cli/.env"
  environment:
    LANG: en_US.utf-8
    LC_ALL: en_US.utf-8
  tags: init

- name: Pause to make sure skale-admin exchange certs with sgx server
  pause:
    seconds: 60
  tags: init
