- name: Assert that Skale Manager contract address is defined on localhost
  assert:
    that:
      - hostvars['localhost']['sm_address'] is defined
      - hostvars['localhost']['sm_address'] | length > 0
    fail_msg: "Required variable 'sm_address' is not defined on localhost or is empty."
    quiet: yes
  tags: contracts

- name: Set hosts
  set_fact: hosts="{{ hosts|default([]) + [ item.value['ansible_host'] ] }}"
  with_dict: "{{ hostvars }}"
  tags: save_base_keys

- name: Execute setup_validator script
  script: setup_validator.py
  environment:
    BASE_DIR: "files"
    ETH_AMOUNT: "0.2"
    ETH_PRIVATE_KEY: "{{ eth_private_key }}"
    ENDPOINT: "{{ endpoint }}"
    MIN_DELEGATION_AMOUNT: "0"
    MANAGER_CONTRACTS: "{{ hostvars['localhost']['sm_address'] }}"
    COMMISSION_RATE: "1"
    NODES_NUMBER: "{{ hosts|length }}"
  args:
    executable: python3
  tags: setup_validators
