- name: Set SM download URL
  set_fact:
    manager_contracts: "{{ sm_url }}"
  when: manager_contracts is undefined

- name: Crash if no SM ABIs URL provided
  fail:
    msg: manager_contracts is undefined
  when: manager_contracts is undefined

- name: Download contracts to the local machine
  get_url:
      url: "{{ manager_contracts }}"
      dest: "files/manager.json"
      mode: 0644

- name: Set hosts
  set_fact: hosts="{{ hosts|default([]) + [ item.value['ansible_host'] ] }}"
  with_dict: "{{ hostvars }}"
  tags: save_base_keys

- name: Execute setup_validator script
  script: setup_validator.py
  environment:
    BASE_DIR: "files"
    ETH_AMOUNT: "0.2"
    ETH_PRIVATE_KEY: "{{ eth_private_key }}"
    ENDPOINT: "{{ endpoint }}"
    MIN_DELEGATION_AMOUNT: "0"
    COMMISSION_RATE: "1"
    NODES_NUMBER: "{{ hosts|length }}"
  args:
    executable: python3
  tags: setup_validators
