# --- Download binary ---

- name: Download skale_cli from spaces (SKALE CLI)
  get_url:
    url: "{{ skale_cli_url }}"
    dest: "/usr/local/bin/skale"
    force: yes
    mode: "0755"
  when:
    - node_type == "skale"
    - build_type == "git"
  tags: binary

- name: Download mirage_cli from spaces
  get_url:
    url: "{{ mirage_cli_url }}"
    dest: "/usr/local/bin/mirage"
    force: yes
    mode: "0755"
  when:
    - node_type == "mirage_boot"
    - build_type == "git"
  tags: binary


# --- Build binary from source ---

- name: Makedir dist (for SKALE CLI build)
  file:
    state: directory
    path: "{{ base_path }}/node-cli/dist"
  when:
    - build_type == "source"

- name: Remove old binary builder image (for SKALE CLI build)
  community.docker.docker_image:
    name: "node-cli-builder"
    state: absent
  when:
    - build_type == "source"

- name: Build binary builder image (for SKALE CLI build)
  community.docker.docker_image_build:
    name: "node-cli-builder"
    network: host
    path: "{{ base_path }}/node-cli"
  when:
    - build_type == "source"

- name: Set build command (for SKALE CLI - regular)
  set_fact:
    build_cmd: "scripts/build.sh test test normal"
  when:
    - node_type == "skale"
    - build_type == "source"
    - sync_node is not defined or not sync_node

- name: Set build command (for Mirage CLI)
  set_fact:
    build_cmd: "scripts/build.sh test test mirage"
  when:
    - node_type == "mirage_boot" or node_type == "mirage"
    - build_type == "source"
    - sync_node is not defined or not sync_node


- name: Add sync option to command (for SKALE CLI - sync)
  set_fact:
    build_cmd: "scripts/build.sh test test sync"
  when:
    - node_type == "skale"
    - build_type == "source"
    - sync_node is defined and sync_node

- name: Build binary
  docker_container:
    image: node-cli-builder
    name: node-cli-builder
    detach: false
    volumes:
      - "{{ base_path }}/node-cli/dist:/app/dist"
    command: "{{ build_cmd }}"
  when:
    - build_type == "source"

- name: Copy executable to /usr/bin/local for normal SKALE CLI
  copy:
    remote_src: True
    src: "{{ base_path }}/node-cli/dist/skale-test-Linux-x86_64"
    dest: /usr/local/bin/skale
    mode: "0755"
  when:
    - node_type == "skale"
    - build_type == "source"
    - (sync_node is not defined or not sync_node)

- name: Copy executable to /usr/bin/local for normal Mirage CLI
  copy:
    remote_src: True
    src: "{{ base_path }}/node-cli/dist/skale-test-Linux-x86_64-mirage"
    dest: /usr/local/bin/mirage
    mode: "0755"
  when:
    - (node_type == "mirage" or node_type == "mirage_boot")
    - build_type == "source"
    - (sync_node is not defined or not sync_node)


- name: Copy executable to /usr/bin/local for sync SKALE CLI
  copy:
    remote_src: True
    src: "{{ base_path }}/node-cli/dist/skale-test-Linux-x86_64-sync"
    dest: /usr/local/bin/skale
    mode: "0755"
  when:
    - node_type == "skale"
    - build_type == "source"
    - sync_node is defined and sync_node

- name: Remove builder container (for SKALE CLI)
  docker_container:
    state: absent
    name: node-cli-builder
  when:
    - build_type == "source"
