- name: Makedir dist
  file:
    state: directory
    path: "{{ base_path }}/node-cli/dist"
  when: env is defined and env == "dev"


- name: Build binary builder image
  community.docker.docker_image_build:
    name: "node-cli-builder"
    path: "{{ base_path }}/node-cli"
  when: env is defined and env == "dev"


- name: Set build command
  set_fact:
    build_cmd: "scripts/build.sh test test"
  when: env is defined and env == "dev"


- name: Add sync option
  set_fact:
    build_cmd: "{{ build_cmd }} sync"
  when: env is defined and env == "dev" and sync_node is defined and sync_node == 'True'


- name: Build binary
  docker_container:
    image: node-cli-builder
    name: node-cli-builder
    detach: false
    volumes:
      - "{{ base_path }}/node-cli/dist:/app/dist"
    command: "{{ build_cmd }}"
  when: env is defined and env == "dev"


- name: Copy executable to /usr/bin/local
  copy: remote_src=True src="{{ base_path }}/node-cli/dist/skale-test-Linux-x86_64" dest=/usr/local/bin/skale
  when: env is defined and env == "dev"


- name: Remove builder container
  docker_container:
    state: absent
    name: node-cli-builder
  when: env is defined and env == "dev"


- name: Download skale_cli from spaces
  get_url:
    url: "{{ skale_cli_url }}"
    dest: "/usr/local/bin/skale"
    force: yes
    mode: 644
  when: env is defined and env == "test"
  tags: binary


- name: Add execute permission to skale executable
  file:
    path: /usr/local/bin/skale
    mode: '0555'
  tags: binary


- name: Register skale command
  set_fact:
    skale: "/usr/local/bin/skale"
  tags: binary
