- name: Save folder name for nodes addresses info
  set_fact:
    node_info_dir: "files/node-info"

- name: Create folder for nodes addresses info
  file:
    path: "{{ node_info_dir }}"
    state: directory
    mode: 0755
  delegate_to: localhost

- name: Get validator id
  set_fact:
    validator_id: "{{ lookup('file', 'files/validator-id.txt') }}"

- name: Show Validator Id
  debug:
    msg: "{{ validator_id }}"

- name: Get wallet info
  command:
    cmd: "{{ node_commands[node_type] }}"
  vars:
    node_commands:
      mirage_boot: "sudo mirage wallet info -f json"
      skale: "sudo skale wallet info -f json"
  when: node_type in node_commands
  register: wallet_info_cmd
  changed_when: false

- name: Show wallet info command output
  debug:
    msg: "{{ wallet_info_cmd.stdout }}"

- name: Get wallet data from json
  set_fact:
    wallet_data: "{{ wallet_info_cmd.stdout | to_json | from_json }}"

- name: Get node signature
  command:
    cmd: "{{ node_commands[node_type] }}"
  vars:
    node_commands:
      mirage_boot: "sudo mirage boot signature {{ validator_id }}"
      skale: "sudo skale node signature {{ validator_id }}"
  when: node_type in node_commands
  register: get_signature_cmd
  changed_when: false

- name: Display node signature
  debug:
    msg: "{{ get_signature_cmd.stdout }}"

- name: Get wallet data from json
  set_fact:
    signature: "{{ get_signature_cmd.stdout.split()[1] }}"

- name: Save address and signature to a file
  copy:
    content: "{{ wallet_data.address}} {{ signature }}"
    dest: "{{ node_info_dir }}/{{ inventory_hostname }}"
  delegate_to: "127.0.0.1"
