- name: Destroy geth container
  become: true
  docker_container:
    name: "geth"
    state: absent
    force_kill: yes
    keep_volumes: no
  tags: geth


- name: Remove geth-signer directory
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ base_path }}/geth-signer"
  tags: geth


- name: Remove iptables rules
  ansible.builtin.iptables:
    chain: "{{ item }}"
    flush: yes
  with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]
