- name: Synchronization of skale-admin repo
  synchronize:
    src: "{{ skale_admin_path }}"
    dest: "{{ base_path }}"
    delete: yes
    recursive: yes
  tags: admin

- name: Synchronization of transaction-manager repo
  synchronize:
    src: "{{ transaction_manager_path }}"
    dest: "{{ base_path }}"
    delete: yes
    recursive: yes
  tags: tm

- name: Synchronization of skale-watchdog repo
  synchronize:
    src: "{{ skale_watchdog_path }}"
    dest: "{{ base_path }}"
    delete: yes
    recursive: yes
  tags: watchdog

- name: Synchronization of skale-node repo
  synchronize:
    src: "{{ skale_node_path }}"
    dest: "{{ base_path }}"
    delete: yes
    recursive: yes
  tags: skale-node

- name: Synchronization of node-cli repo
  synchronize:
    src: "{{ skale_node_cli_path }}"
    dest: "{{ base_path }}"
    delete: yes
    recursive: yes
  tags: cli

- name: Synchronization of bounty-agent repo
  synchronize:
    src: "{{ bounty_agent_path }}"
    dest: "{{ base_path }}"
    delete: yes
    recursive: yes
  when:
    - node_type == "skale"
  tags: bounty

- name: Replace skale-node docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ base_path }}/skale-node/docker-compose.yml"
  when:
    - node_type == "skale"

- name: Replace mirage-node docker-compose-mirage file
  template:
    src: docker-compose-mirage.yml.j2
    dest: "{{ base_path }}/skale-node/docker-compose-mirage.yml"
  when:
    - node_type in ['mirage_boot', 'mirage']

- name: Replace skale-node docker-compose-sync file
  template:
    src: docker-compose-sync.yml.j2
    dest: "{{ base_path }}/skale-node/docker-compose-sync.yml"
  when:
    - node_type == "skale"
    - sync_node is defined and sync_node
