- name: Cleanup contracts - remove all chains
  script:
    cmd: cleanup_contracts.py remove_chains
  run_once: yes
  environment:
    BASE_DIR: "files"
    ETH_PRIVATE_KEY: "{{ eth_private_key }}"
    ENDPOINT: "{{ endpoint }}"
    MANAGER_CONTRACTS: "{{ manager_contracts }}"
  args:
    executable: python3
  tags:
    - cleanup_chains

- name: Cleanup contracts - remove all active nodes
  ansible.builtin.script:
    cmd: cleanup_contracts.py remove_nodes
  run_once: yes
  environment:
    BASE_DIR: "files"
    ETH_PRIVATE_KEY: "{{ eth_private_key }}"
    ENDPOINT: "{{ endpoint }}"
    MANAGER_CONTRACTS: "{{ manager_contracts }}"
  args:
    executable: python3
  tags:
    - cleanup_nodes
