- name: Choose SSL generator
  set_fact:
    ssl_generator: "{{ groups['nodes'][0] }}"

- import_tasks: install.yaml
  when: local_src is not defined or local_src
  run_once: true
  delegate_to: "{{ ssl_generator }}"
  tags: certbot_install

- import_tasks: do_api.yaml
  when: local_src is not defined or local_src
  run_once: true
  delegate_to: "{{ ssl_generator }}"
  tags: do_configure

- import_tasks: ensure.yaml
  when: local_src is not defined or local_src
  run_once: true
  delegate_to: "{{ ssl_generator }}"
  tags: certbot_generate

- import_tasks: hook.yaml
  when: local_src is not defined or local_src
  run_once: true
  delegate_to: "{{ ssl_generator }}"
  tags: certbot_generate

  # - import_tasks: prepare.yaml
  #   when: local_src is not defined or local_src
  #   tags: ssl_prepare
  #
  # - import_tasks: sync.yaml
  #   when: local_src is defined and not local_src
  #   tags: ssl_prepare

  # - import_tasks: dns.yaml
  #   when: do_token is defined and do_token
  #   tags: dns
