- name: Set sync_flags based on sync_node and catchup status
  set_fact:
    sync_flags: "{{ '--catchup' if (sync_node | default(false) | bool) and (catchup | default(false) | bool) else '' }}"

- name: Add --archive if needed (SKALE sync node)
  set_fact:
    sync_flags: "{{ sync_flags }} --archive"
  when:
    - node_type == "skale"
    - sync_node is defined and sync_node
    - archive is defined and archive

- name: Add --historic-state if needed (SKALE sync node)
  set_fact:
    sync_flags: "{{ sync_flags }} --historic-state"
  when:
    - node_type == "skale"
    - sync_node is defined and sync_node
    - historic_state is defined and historic_state

- name: Build and execute init command
  command:
    cmd: "{{ command_prefixes[node_type] }} init {{ base_path }}/init-env {{ sync_flags }}"
  vars:
    command_prefixes:
      mirage_boot: "mirage boot"
      mirage: "mirage node"
      skale: "{{ 'skale sync-node' if (sync_node | default(false) | bool) else 'skale node' }}"
  when: node_type in command_prefixes
  register: init_cmd

- name: Show init command output
  debug:
    msg: "{{ init_cmd.stdout }}"

- name: Pause to make sure skale-admin exchange certs with sgx server
  pause:
    seconds: 120
