- name: Define cmd for mirage boot node
  set_fact:
    cli_full_command: "{{ node_type }} boot init {{ base_path }}/init-env"
  when: node_type is defined and node_type == "mirage"

- name: Define cmd for regular SKALE node
  set_fact:
    cli_full_command: "{{ node_type }} node init {{ base_path }}/init-env"
  when:
    - node_type is not defined or node_type != "mirage"
    - sync_node is not defined or not sync_node

- name: Define cmd for SKALE sync node
  set_fact:
    cli_full_command: "{{ node_type }} sync-node init {{ base_path }}/init-env"
  when:
    - node_type is not defined or node_type != "mirage"
    - sync_node is defined and sync_node

- name: Add --catchup if needed (SKALE sync node)
  set_fact:
    cli_full_command: "{{ cli_full_command }} --catchup"
  when:
    - node_type is not defined or node_type != "mirage"
    - sync_node is defined and sync_node
    - catchup is defined and catchup

- name: Add --archive if needed (SKALE sync node)
  set_fact:
    cli_full_command: "{{ cli_full_command }} --archive"
  when:
    - node_type is not defined or node_type != "mirage"
    - sync_node is defined and sync_node
    - archive is defined and archive

- name: Add --historic-state if needed (SKALE sync node)
  set_fact:
    cli_full_command: "{{ cli_full_command }} --historic-state"
  when:
    - node_type is not defined or node_type != "mirage"
    - sync_node is defined and sync_node
    - historic_state is defined and historic_state

- name: Show cli_full_command
  debug:
    msg: "{{ cli_full_command }}"

- name: Execute cli_full_command
  command:
    cmd: "{{ cli_full_command }}"
  environment:
    LANG: en_US.utf-8
    LC_ALL: en_US.utf-8

- name: Pause to make sure skale-admin exchange certs with sgx server
  pause:
    seconds: 120
  tags: init
