- name: Set IMA contract address
  set_fact:
    ima_contracts: "{{ hostvars['localhost']['ima_address'] }}"
  when: ima_contracts is undefined
  tags: contracts

- name: Crash if no IMA contract address provided
  fail:
    msg: ima_contracts is undefined
  when: ima_contracts is undefined
  tags: contracts

- name: Set sgx url
  set_fact:
    sgx_url: "https://{{ hostvars['sgx0'].ansible_host }}:1026"
  when: sgx_url is not defined or sgx_url == ''

- name: Set env options for Mirage node
  set_fact:
    env_options: |
      MANAGER_CONTRACTS="{{ manager_contracts }}"
      IMA_CONTRACTS="{{ ima_contracts }}"
      CONTAINER_CONFIGS_STREAM="{{ container_configs_stream }}"
      ENDPOINT="{{ endpoint }}"
      CONTAINER_CONFIGS_DIR="{{ container_configs_dir if (build_type | default('')) == 'source' else ''}}"
      DISK_MOUNTPOINT="{{ block_device }}"
      SGX_SERVER_URL="{{ sgx_url }}"
      ENV_TYPE="{{ env_type }}"
      FILEBEAT_HOST="{{ filebeat_host }}"
      ENFORCE_BTRFS='False'
  when: node_type == "mirage_boot"
  tags: env

- name: Set env options for regular SKALE node
  set_fact:
    env_options: |
      ENDPOINT="{{ endpoint }}"
      IMA_ENDPOINT="{{ ima_endpoint }}"
      CONTAINER_CONFIGS_STREAM="{{ container_configs_stream }}"
      FILEBEAT_HOST="{{ filebeat_host }}"
      MANAGER_CONTRACTS="{{ manager_contracts }}"
      IMA_CONTRACTS="{{ ima_contracts }}"
      CONTAINER_CONFIGS_DIR="{{ container_configs_dir if (build_type | default('')) == 'source' else ''}}"
      DOCKER_LVMPY_STREAM="{{ docker_lvmpy_stream }}"
      DISK_MOUNTPOINT="{{ block_device }}"
      SGX_SERVER_URL="{{ sgx_url }}"
      TG_API_KEY="{{ tg_api_key }}"
      TG_CHAT_ID="{{ tg_chat_id }}"
      MONITORING_CONTAINERS="{{ monitoring_containers }}"
      DEFAULT_GAS_PRICE_WEI="{{ default_gas_price_wei }}"
      ENV_TYPE="{{ env_type }}"
      DISABLE_IMA="{{ disable_ima }}"
      INFLUX_URL="{{ influx_url }}"
      TELEGRAF="{{ telegraf }}"
  when:
    - node_type == "skale"
    - (sync_node is not defined or not sync_node)
  tags: env

- name: Set env options for SKALE sync node
  set_fact:
    env_options: |
      CONTAINER_CONFIGS_STREAM="{{ container_configs_stream }}"
      CONTAINER_CONFIGS_DIR="{{ container_configs_dir }}"
      ENDPOINT={{ endpoint }}
      ENFORCE_BTRFS='True'
      DOCKER_LVMPY_STREAM="{{ docker_lvmpy_stream }}"
      ENV_TYPE="{{ env_type }}"
      SCHAIN_NAME="{{ schain_name }}"
      MANAGER_CONTRACTS={{ manager_contracts }}
      IMA_CONTRACTS={{ ima_contracts }}
      DISK_MOUNTPOINT={{ block_device }}
      INFLUX_URL="{{ influx_url }}"
      TELEGRAF="{{ telegraf }}"
  when:
    - node_type == "skale"
    - (sync_node is defined and sync_node)
  tags: env

- name: Show env
  debug:
    msg: "{{ env_options }}"

- name: Save new init-env
  copy:
    content: "{{ env_options }}"
    dest: "{{ base_path }}/init-env"
