- name: Set ssl folder
  set_fact:
    host_ssl: "{{ base_path }}/ssl/{{ inventory_hostname }}"

- name: Upload SSL certificates to the node
  command: "skale ssl upload -c {{ host_ssl }}/fullchain.pem -k {{ host_ssl }}/privkey.pem -f"

- name: Set domain name
  command: "sudo skale node set-domain -d {{ domain }} --yes"
  tags:
    domain
