- name: Check if certificate already exists
  stat:
    path: /etc/letsencrypt/live/{{ domain }}/cert.pem
  register: cert

- name: Generate new certificate if one doesn't exist
  command: |
    certbot certonly -n --dns-digitalocean --dns-digitalocean-credentials {{ do_config }} -d {{ domain }} -m {{ email }} --agree-tos
  when: not cert.stat.exists

- name: Test renewal procedure
  command: "certbot renew --dns-digitalocean --dns-digitalocean-credentials {{ do_config }} -d {{ domain }}"
  when: cert.stat.exists and test_renewal is defined and test_renewal

- name: Run renewal procedure
  command: "certbot renew --quiet --dns-digitalocean --dns-digitalocean-credentials {{ do_config }}"
  when: cert.stat.exists
