- name: Define nginx reload hook file
  set_fact:
    nginx_reload_hook: "/etc/letsencrypt/renewal-hooks/deploy/reload_nginx"

- name: Setup hook to reload nginx container
  copy:
    content: |
      #!/usr/bin/env bash
      set -e
      cp /etc/letsencrypt/live/{{ domain }}/fullchain.pem {{ base_path }}/{{ domain }}/ssl/server.crt && \
      cp /etc/letsencrypt/live/{{ domain }}/privkey.pem {{ base_path }}/{{ domain }}/ssl/server.key && \
      skale ssl upload -c {{ base_path }}/ssl/{{ domain }}/server.crt -k {{ base_path }}/ssl/{{ domain }}/server.key
    dest: "{{ nginx_reload_hook }}"
    mode: "0750"
