- import_tasks: install.yaml
  when: cert_mode == "certbot"
  tags: certbot_install

- import_tasks: do.yaml
  when: cert_mode == "certbot"
  tags: do_configure

- import_tasks: ensure.yaml
  when: cert_mode == "certbot"
  tags: certbot_generate

- import_tasks: hook.yaml
  when: cert_mode == "certbot"
  tags: certbot_generate

- import_tasks: prepare.yaml
  when: cert_mode == "certbot"
  tags: ssl_prepare

- import_tasks: sync.yaml
  when: cert_mode == "custom"
  tags: ssl_sync

- import_tasks: configure.yaml
  tags: ssl_configure
