- import_tasks: ssh_keys.yaml
  tags: ssh

- import_tasks: swap.yaml
  tags: swap

- name: Set soft ulimits
  pam_limits:
    domain: root
    limit_type: soft
    limit_item: core
    value: "1000000000"
  tags: ulimits

- name: Set hard ulimits
  pam_limits:
    domain: root
    limit_type: hard
    limit_item: core
    value: "1000000000"
  tags: ulimits

- name: Install packages
  apt: name={{ item }} update_cache=yes state=latest
  loop: [
    "apt-transport-https",
    "ca-certificates",
    "curl",
    "software-properties-common",
    "virtualenv",
    "python3-setuptools",
    "python3-dev",
    "iptables-persistent",
    "python3-pip"
    ]
  tags: apt

- import_tasks: docker.yaml
  tags: docker

- name: Update pip
  pip:
    name: pip
    state: latest

- name: Uninstall pyOpenSSL
  pip:
    name: pyOpenSSL
    state: absent
  tags:
    - pip
    - openssl

- name: Sync requirements to remote machine
  copy:
    src: files/remote-requirements.txt
    dest: "{{ base_path }}/requirements.txt"
  tags: pip

- name: Install requirements
  pip:
    requirements: "{{ base_path }}/requirements.txt"
  tags: pip

- name: Enable timedatectl
  shell: sudo timedatectl set-ntp on
  become: true
  tags: ntp

- name: Enable timesyncd service
  systemd:
    name: systemd-timesyncd
    state: started
  become: true
  tags: ntp
