- name: Register swap_file name
  set_fact:
    swap_file: "/swapfile"
  tags:
    - swap_var

- name: Register swap_file_size (double RAM)
  set_fact:
    swap_file_size: "{{ (ansible_memtotal_mb * 1024 * 1024 * 0.5) | int | abs }}"
  tags:
    - swap_var

- name: Register swapiness
  set_fact:
    swappiness: "{{ 60 | int }}"
  tags:
    - swap_var

- name: Check if swap file exists
  stat:
    path: "{{ swap_file }}"
  register: swap_file_check
  tags:
    - swap_file_check

- name: Create swap file
  command: fallocate -l {{ swap_file_size }} {{ swap_file }}
  when: not swap_file_check.stat.exists
  tags:
    - swap_file_create

- name: Change swap file permissions
  file: path="{{ swap_file }}"
        owner=root
        group=root
        mode=0600
  tags:
    - swap
    - swap_file_permissions

- name: Format swap file
  command: "mkswap {{ swap_file }}"
  when: not swap_file_check.stat.exists
  tags:
    - swap_mkswap

- name: Write swap entry in fstab
  mount: name=none
         src={{ swap_file }}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
  tags:
    - swap_fstab

- name: Turn on swap
  command: swapon -a
  when: not swap_file_check.stat.exists
  tags:
    - swap_turn_on

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swappiness }}"
  tags:
    - set_swappiness
