- name: Run skale node init
  command: 
    chdir: "{{ base_path }}/skale-node-cli"
    cmd: "skale node init  --install-deps --env-file {{ base_path }}/skale-node-cli/.env"
  environment:
    LANG: en_US.utf-8
    LC_ALL: en_US.utf-8

- name: Pause to make sure skale-admin exchange certs with sgx server
  pause:
    seconds: 60

- name: Get token.json output 
  command: cat "{{ base_path }}/.skale/node_data/tokens.json"
  register: token_output 
  tags:
    user_register

- name: Set user token
  set_fact: 
    user_token: "{{ item.value }}"
  with_dict: "{{ token_output.stdout | from_json }}"
  tags:
    user_register

- name: Debug
  debug: msg="{{ user_token }}"
  tags:
    user_register

- name: Run skale user register
  command: 
    chdir: "{{ base_path }}/skale-node-cli"
    cmd: "skale user register --username test --password test --token {{ user_token }}" 
  environment:
    LANG: en_US.utf-8
    LC_ALL: en_US.utf-8
  tags:
    user_register

