- name: Fair migrate
  command:
    cmd: "fair node migrate {{ base_path }}/init-env --yes"
  register: migrate_cmd

- name: Show migrate command output
  debug:
    msg: "{{ migrate_cmd.stdout }}"

- name: Execute set_rng script
  script: set_rng.py
  environment:
    BASE_DIR: "files"
    ETH_PRIVATE_KEY: "{{ eth_private_key }}"
    ENDPOINT: "{{ boot_endpoint }}"
    FAIR_CONTRACTS: "{{ fair_contracts }}"
  args:
    executable: python3
  delegate_to: localhost
  run_once: true
  become: false
  tags: set_rng
  when: set_rng_script_has_run is not defined

- name: Mark set_rng script as executed
  set_fact:
    set_rng_script_has_run: true
  run_once: true

- name: Stop and remove anvil container
  docker_container:
    name: anvil
    state: absent
  delegate_to: "{{ groups['nodes'][0] }}"
  run_once: true
  when: anvil is defined and anvil
  tags: stop_anvil
