- name: Download contracts from digitalocean
  get_url:
    url: "{{ manager_contracts }}"
    dest: "{{ base_path }}/manager.json"
    mode: 0644
    force: true
  tags:
    contracts

- name: Synchronization of skale-admin repo
  synchronize:
    src: "{{ skale_admin_path }}"
    dest: "{{ base_path }}"
    delete: yes
    recursive: yes
  when: env is defined and env == "dev"
  tags: admin

- name: Synchronization of transaction-manager repo
  synchronize:
    src: "{{ transaction_manager_path }}"
    dest: "{{ base_path }}"
  when: env is defined and env == "dev"
  tags: tm

- name: Synchronization of skale-node repo
  synchronize:
    src: "{{ skale_node_path }}"
    dest: "{{ base_path }}"

- name: Synchronization of node-cli repo
  synchronize:
    src: "{{ skale_node_cli_path }}"
    dest: "{{ base_path }}"
  when: env is defined and env == "dev"
  tags: cli

- name: Replace skale-node docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ base_path }}/skale-node/docker-compose.yml"
  when: env is defined and env == "dev"

- name: Remove existent .env content
  shell: "echo '' > {{ base_path }}/init-env"

  # - name: Get block device from lvm-block-device file created by terraform
  #   shell: cat "{{ base_path }}/lvm-block-device"
  #   register: block_device

- name: Write variables to .env file
  lineinfile:
    path: "{{ base_path }}/init-env"
    insertbefore: BOF
    line: "{{ item.name }}={{ item.value }}"
  with_items:
    - { name: ENDPOINT, value: "{{ endpoint }}"}
    - { name: IMA_ENDPOINT, value: "{{ ima_endpoint }}"}
    - { name: DB_USER, value: "{{ db_user }}"}
    - { name: DB_PASSWORD, value: "{{ db_password }}"}
    - { name: DB_ROOT_PASSWORD, value: "{{ db_root_password }}"}
    - { name: DB_PORT, value: "{{ db_port }}"}
    - { name: CONTAINER_CONFIGS_STREAM, value: "{{ container_configs_stream }}"}
    - { name: FILEBEAT_HOST, value: "{{ filebeat_host }}"}
    - { name: MANAGER_CONTRACTS_ABI_URL, value: "{{ manager_contracts }}"}
    - { name: IMA_CONTRACTS_ABI_URL, value: "{{ ima_contracts }}"}
    - { name: CONTAINER_CONFIGS_DIR, value: "{{ container_configs_dir }}"}
    - { name: DOCKER_LVMPY_STREAM, value: "{{ docker_lvmpy_stream }}"}
    # - { name: DISK_MOUNTPOINT, value: "{{ block_device.stdout }}"}
    - { name: DISK_MOUNTPOINT, value: "{{ block_device }}"}
    - { name: SGX_SERVER_URL, value: "{{ sgx_url }}"}
    - { name: TG_API_KEY, value: "{{ tg_api_key }}"}
    - { name: TG_CHAT_ID, value: "{{ tg_chat_id }}"}
    - { name: MONITORING_CONTAINERS, value: "{{ monitoring_containers }}"}
    - { name: DEFAULT_GAS_PRICE_WEI, value: "{{ default_gas_price_wei }}"}
    - { name: ENV_TYPE, value: "{{ env_type }}"}
    - { name: DISABLE_IMA, value: "{{ disable_ima }}"}
