- name: Install requirements
  command:
    chdir: "{{ base_path }}/node-cli/"
    cmd: "pip3 install -e '.'"
  when: env is defined and env == "dev"

- name: Install setuptools 39-0-1
  pip:
    name: setuptools==39.0.1
    state: forcereinstall
  tags:
    pip

- name: Register skale command
  set_fact:
    skale: "{{ base_path }}/cli-venv/bin/python main.py"
  when: env is defined and env == "dev"

- name: Build skale command
  command:
    cmd: "bash scripts/build.sh 0.0.0 test"
    chdir: "{{ base_path }}/node-cli"
  when: env is defined and env == "dev"

- name: Copy executable to /usr/bin/local
  copy: remote_src=True src="{{ base_path }}/node-cli/dist/skale-0.0.0-Linux-x86_64" dest=/usr/local/bin/skale
  when: env is defined and env == "dev"

- name: Download skale_cli from spaces
  get_url:
    url: "{{ skale_cli_url }}"
    dest: "/usr/local/bin/skale"
    force: yes
    mode: 644
  when: env is defined and env == "test"
  tags: binary

- name: Add execute permission to skale executable
  file:
    path: /usr/local/bin/skale
    mode: '0555'
  tags: binary

- name: Register skale command
  set_fact:
    skale: "/usr/local/bin/skale"
  tags: binary
