- name: Register node that was exited
  hosts: nodes
  become: true
  tasks:
    - import_role: 
        name: cleanup
        tasks_from: node_config

    - import_role:
        name: update
        tasks_from: skale_update
      
    - import_role: 
        name: validators
        tasks_from: link_addresses.yaml
       
    - import_role: 
        name: register
