- name: Setup skale node
  hosts: nodes
  become: true
  roles:
    - role: sources
      tags: 
        - sync
        - source

    - role: skale-cli
      tags: cli

    - role: init
      tags: 
        - init
