- name: Build and execute cleanup command
  command:
    cmd: "{{ command_prefixes[node_type] }} cleanup --yes"
  vars:
    command_prefixes:
      fair: "{{ 'fair passive-node' if (passive_node | default(false) | bool) else 'fair node' }}"
      skale: "{{ 'skale passive-node' if (passive_node | default(false) | bool) else 'skale node' }}"
  when: node_type in command_prefixes
  register: cleanup_cmd

- name: Show cleanup command output
  debug:
    msg: "{{ cleanup_cmd.stdout }}"
