- name: Build and execute cleanup command
  command:
    cmd: "{{ command_prefixes[node_type] }} node cleanup --yes"
  vars:
    command_prefixes:
      fair: "fair"
  when: node_type in command_prefixes
  register: cleanup_cmd

- name: Show cleanup command output
  debug:
    msg: "{{ cleanup_cmd.stdout }}"
