- name: Get all container ids
  command: "docker ps -aq"
  become: true
  register: containers_output
  tags:
    - cleanup

- name: Split containers ids output
  register: containers_output
  set_fact:
    containers_ids: "{{ containers_output.stdout.split('\n') }}"
  tags:
    - cleanup

- name: Destroy admin container
  become: true
  docker_container:
    name: "skale_admin"
    state: absent
    force_kill: yes
    keep_volumes: no
  tags:
    - cleanup
    - admin

- name: Destroy all containers
  become: true
  docker_container:
    name: "{{ item }}"
    state: absent
    force_kill: yes
    keep_volumes: no
  with_items: "{{ containers_ids | default([]) }}"
  tags:
    - cleanup

- name: Prune docker
  command:
    cmd: "docker system prune -af"
  tags:
    - cleanup
    - containers_artifacts

- name: Umount shared-space
  command:
    cmd: "umount /mnt/schains-shared-space"
  failed_when: False

- name: Register /mnt folders
  find:
    paths: "/mnt/"
    file_type: any
  register: mnt_folders
  tags:
    - cleanup
    - mounts

- name: Cleanup /mnt dir
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ mnt_folders.files }}"
  tags:
    - cleanup
    - mounts

- name: Remove all volumes
  lvg:
    vg: "schains"
    state: absent
    force: yes
  tags:
    - cleanup
    - volumes
