- name: Run container cleanup
  import_tasks: containers.yaml
  tags: container_cleanup

- name: Run docker-lvmpy cleanup
  import_tasks: docker_lvmpy.yaml
  tags: lvmpy_cleanup

- name: Run node artifacts cleanup
  import_tasks: node_artifacts.yaml
  tags: node_cleanup

- name: Run docker cleanup
  import_tasks: docker.yaml
  tags: docker_cleanup
