- name: Run skale node update
  shell:
    cmd: "skale node update {{ base_path }}/init-env --yes"
  environment:
    LANG: en_US.utf-8
    LC_ALL: en_US.utf-8
    HOME_DIR: "{{ base_path }}"
  tags: skale_update
