- name: Sync docker-compose.yml
  synchronize:
    src: "{{ base_path }}/skale-node/docker-compose.yml"
    dest: "{{ base_path }}/.skale/config/docker-compose.yml"
  delegate_to: "{{ inventory_hostname }}"

- name: Sync containers.json
  synchronize:
    src: "{{ base_path }}/skale-node/containers.json"
    dest: "{{ base_path }}/.skale/config/containers.json"
  delegate_to: "{{ inventory_hostname }}"

- name: Sync schain_allocation.yml
  synchronize:
    src: "{{ base_path }}/skale-node/schain_allocation.yml"
    dest: "{{ base_path }}/.skale/config/schain_allocation.yml"
  delegate_to: "{{ inventory_hostname }}"
