- name: Update node based on its type
  block:
    - name: Determine the correct update command
      set_fact:
        update_cmd: >-
          {% set sync = sync_node | default(false) | bool %}
          {% if node_type == 'mirage_boot' %}
          mirage boot update {{ base_path }}/init-env --yes
          {% elif node_type == 'skale' and sync %}
          skale sync-node update {{ base_path }}/init-env --yes --unsafe
          {% elif node_type == 'skale' and not sync %}
          skale node update {{ base_path }}/init-env --yes --pull-config all --unsafe
          {% else %}
          ""
          {% endif %}

    - name: Fail if update command could not be determined
      fail:
        msg: "Could not determine update command for node_type='{{ node_type }}' and sync_node='{{ sync_node | default('not defined') }}'."
      when: update_cmd | length == 0

    - debug:
        msg: "{{ update_cmd }}"

    - name: Run the determined node update command
      shell:
        cmd: "{{ update_cmd }}"
      environment:
        HOME_DIR: "{{ base_path }}"
  tags: skale_update