- name: Run skale node update
  shell:
    cmd: "skale node update {{ base_path }}/init-env --yes"
  environment:
    LANG: en_US.utf-8
    LC_ALL: en_US.utf-8
    HOME_DIR: "{{ base_path }}"
  when: sync_node is not defined or not sync_node
  tags: skale_update

- name: Run skale sync node update
  shell:
    cmd: "skale sync-node update {{ base_path }}/init-env --yes"
  environment:
    LANG: en_US.utf-8
    LC_ALL: en_US.utf-8
    HOME_DIR: "{{ base_path }}"
  when: sync_node is defined and sync_node
  tags: skale_update
