- name: Register ip address
  set_fact:
    ip_address: "{{ hostvars[inventory_hostname].ansible_host }}"

- name: Compose register command
  set_fact:
    node_register_command: >-
      {% if node_type == "mirage" %}
      {{ node_type }} boot register -n {{ inventory_hostname }} --ip {{ ip_address }} -p 10000 --domain {{ inventory_hostname }}.{{ base_domain_name }}
      {% else %}
      {{ node_type }} node register -n {{ inventory_hostname }} --ip {{ ip_address }} -p 10000 --domain {{ inventory_hostname }}.{{ base_domain_name }}
      {% endif %}

- name: Run node register command
  command:
    cmd: "{{ node_register_command }}
  environment:
    LANG: en_US.utf-8
    LC_ALL: en_US.utf-8