- name: Register ip address
  set_fact:
    ip_address: "{{ hostvars[inventory_hostname].ansible_host }}"

- name: Compose register command
  set_fact:
    node_register_command: >-
      {% if node_type == "mirage_boot" %}
      mirage boot register -n {{ inventory_hostname }} --ip {{ ip_address }} -p 10000 -d {{ inventory_hostname }}.{{ base_domain_name }}
      {% elif node_type == "skale" %}
      skale node register -n {{ inventory_hostname }} --ip {{ ip_address }} -p 10000 -d {{ inventory_hostname }}.{{ base_domain_name }}
      {% endif %}

- name: Run node register command
  command:
    cmd: "{{ node_register_command }}
  environment:
    LANG: en_US.utf-8
    LC_ALL: en_US.utf-8