- name: Synchronization of skale-admin repo
  synchronize:
    src: "{{ skale_admin_path }}"
    dest: "{{ base_path }}"
  when: env is defined and env == "dev"
    
- name: Synchronization of transaction-manager repo
  synchronize:
    src: "{{ transaction_manager_path }}"
    dest: "{{ base_path }}"
  when: env is defined and env == "dev"

- name: Synchronization of skale-node repo
  synchronize:
    src: "{{ skale_node_path }}"
    dest: "{{ base_path }}"

- name: Synchronization of skale-node-cli repo
  synchronize:
    src: "{{ skale_node_cli_path }}"
    dest: "{{ base_path }}"
  when: env is defined and env == "dev"

- name: Replace skale-node docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ base_path }}/skale-node/docker-compose.yml"
  when: env is defined and env == "dev"

- name: Remove existent .env content
  shell: "echo '' > {{ base_path }}/init-env"

- name: Get block device from lvm-block-device file created by terraform
  shell: cat "{{ base_path }}/lvm-block-device"
  register: block_device

- name: Write variables to .env file 
  lineinfile:
    path: "{{ base_path }}/init-env"
    insertbefore: BOF
    line: "{{ item.name }}={{ item.value }}"
  with_items:
    - { name: ENDPOINT, value: "{{ endpoint }}"}
    - { name: IMA_ENDPOINT, value: "{{ ima_endpoint }}"}
    - { name: DB_USER, value: "{{ db_user }}"}
    - { name: DB_PASSWORD, value: "{{ db_password }}"}
    - { name: DB_ROOT_PASSWORD, value: "{{ db_root_password }}"}
    - { name: DB_PORT, value: "{{ db_port }}"}
    - { name: DOCKER_USERNAME, value: "{{ docker_username }}"}
    - { name: DOCKER_PASSWORD, value: "{{ docker_password }}"}
    - { name: CONTAINER_CONFIGS_STREAM, value: "{{ container_configs_stream }}"}
    - { name: FILEBEAT_HOST, value: "{{ filebeat_host }}"}
    - { name: MANAGER_CONTRACTS_ABI_URL, value: "{{ manager_contracts }}"}
    - { name: IMA_CONTRACTS_ABI_URL, value: "{{ ima_contracts }}"}
    - { name: CONTAINER_CONFIGS_DIR, value: "{{ container_configs_dir }}"}
    - { name: DOCKER_LVMPY_STREAM, value: "{{ docker_lvmpy_stream }}"}
    - { name: DISK_MOUNTPOINT, value: "{{ block_device.stdout }}"}
    - { name: SGX_SERVER_URL, value: "{{ sgx_url }}"}
