- name: Restore node from AMI
  hosts: nodes
  gather_facts: false
  vars:
    - ip_address: "{{ hostvars[inventory_hostname].ansible_host }}"
  vars_files:
    - "files/node-backup/{{ ip_address }}/aws_info"

  tasks:
    - name: Restore AWS from AMI
      include_role:
        name: aws
        tasks_from: restore
        apply:
          tags: aws
      tags:
        aws
