- name: Propagate manager_contracts to nodes
  hosts: nodes
  gather_facts: no
  tasks:
    - name: Set manager_contracts fact for each node
      set_fact:
        manager_contracts: "{{ hostvars['localhost']['manager_contracts'] | default(manager_contracts, true) }}"
    - name: Crash if no SM contract address/alias provided
      fail:
        msg: manager_contracts is undefined
      when: manager_contracts is undefined

- name: Setup skale node
  hosts: nodes
  become: true
  roles:
    - role: sync
      tags: sync
      when: build_type == "source"

    - role: skale_cli
      tags: cli

    - role: config
      tags: config

    - role: init
      tags: init


- name: Reconfigure firewall rules
  hosts: geth
  become: true
  tasks:
    - name: Configure geth iptables
      import_role:
        name: geth
        tasks_from: firewall
      tags: firewall
