- name: Setup skale node
  hosts: nodes
  become: true
  roles:
    - role: sgx_sim
      when: sgx_sim is defined and sgx_sim == true

    - role: sources
      tags:
        - sync
        - source

    - role: skale_cli
      tags: cli

    - role: init
      tags:
        - init
