- name: Setup sgx simulator
  hosts: nodes
  become: true
  pre_tasks:
    - set_fact:
        sgx_simulator: true
  roles:
    - role: sgx
      tags:
        - sgx
      when: sgx_version is defined
