- name: Update skale node
  hosts: nodes
  become: true
  roles:
    - role: sync
      when: env is defined and env == "dev"
      tags: sync

    - role: config
      tags: config

    - role: update
      tags: update
