- name: Update skale node
  hosts: nodes,archive
  become: true
  roles:
    - role: sync
      when: build_type == "source"
      tags: sync

    - role: config
      tags: config

    - role: update
      tags: update
