name: Build and publish
on:
  pull_request:
    types: [closed]
    branches:
      - master
      - develop
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
    - uses: actions/checkout@v2
    - name: Checkout code
      uses: actions/checkout@master

    - name: Calculate version
      run: |
        export BRANCH=${GITHUB_REF##*/}
        export VERSION=$(cat VERSION)
        echo "Branch: $BRANCH"
        echo "Base version: $VERSION"
        export VERSION=$(bash ./helper-scripts/calculate_version.sh)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Version $VERSION"
        export RELEASE=true
        echo "RELEASE=$RELEASE" >> $GITHUB_ENV
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: ${{ env.VERSION }}
        draft: false
        prerelease: true
