- name: Register ip address
  set_fact:
    ip_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- name: Run skale node register 
  command: 
    cmd: "skale node register --name {{ inventory_hostname }} --ip {{ ip_address }} --port 10000"
  environment:
    LANG: en_US.utf-8
    LC_ALL: en_US.utf-8
